### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS#6]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by josjjara** [comment]
Dear, customer. We have received your new additions to the business rule, we will start working on them to complete them before the milestone.

**Comment by josjjara** [comment]
The issue has been categorized.

**Comment by josjjara** [comment]
We will proceed to process the new request, @STEVEN2199  will be the assigned analyst, @Neoterux  will develop the solution, and @josjjara  will perform the tests.

**Comment by STEVEN2199** [comment]
[Impact analysis - issue #6.docx](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/files/10418394/Impact.analysis.-.issue.6.docx)
Dear, customer. Here is the impact analysis for this issue. @pmaldonado-espol

**Comment by Neoterux** [comment]
@josjjara, @STEVEN2199 There is a first implementation with the new changes on  commit 8e3adfe1c10cf5db82555236215c40cd270921cf. Please check out and test them.
```java
// class: ec.edu.espol.workshops.core.entities.Customer
  @Override
  public long calculateInsuranceValue() throws InsuranceException {
    ...
    if (isMarried && age > 30 && age < 60) {
      premiumCost -= 50;
    }
    if (sex == 'F' && !isMarried && age > 60) {
      premiumCost -= 50;
    }
        return premiumCost;  
  }

  ...
}
```

**Comment by pmaldonado-espol** [comment]
> [Impact analysis - issue #6.docx](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/files/10418394/Impact.analysis.-.issue.6.docx)
> Dear, customer. Here is the impact analysis for this issue. @pmaldonado-espol

that's OK, please go ahead.

**Comment by josjjara** [comment]
Test failed, please check @Neoterux 
[Unit and System Testing Plan.pdf](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/files/10438876/Unit.and.System.Testing.Plan.pdf)

**Comment by Neoterux** [comment]
Hi, I've pushed some changes can you validate the tests @josjjara?

**Comment by josjjara** [comment]
The code now passes all the tests.
[Unit and System Testing Plan V2.pdf](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/files/10439820/Unit.and.System.Testing.Plan.V2.pdf)

**Comment by josjjara** [comment]
Dear customer @pmaldonado-espol , ill attach the acceptance testing plan for the new features and some quick instructions to execute the code if needed. Let me know if more instructions are need or if there's any problems with the acceptance plan.
[Acceptance Testing .pdf](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/files/10440560/Acceptance.Testing.pdf)

**Comment by pmaldonado-espol** [comment]
> Dear customer @pmaldonado-espol , ill attach the acceptance testing plan for the new features and some quick instructions to execute the code if needed. Let me know if more instructions are need or if there's any problems with the acceptance plan.
> [Acceptance Testing .pdf](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/files/10440560/Acceptance.Testing.pdf)

The new insurance calculations are according with the requested changes, thanks.

**Comment by josjjara** [comment]
Thank you @pmaldonado-espol , all the steps have been verified and the solution has been completed. @Neoterux  will release the new software version for you.

**Comment by Neoterux** [comment]
Hi! @pmaldonado-espol, @lemendoza as we have made all the changes requested, we've created a compiled executable of the given program. In order to download an use it refers to [the v1.0 release page](https://github.com/STEVEN2199/ISII-WORKSHOPS-PEDIDOS_BODEGAS_Y_COMPRAS/releases/tag/v1.0), In there is described the *requirements* and the *steps* to follow and run the program.

If you have a question, I'm always available to answer them. Please notify to us any incidence that you could find.

**Comment by josjjara** [comment]
Dear customer @pmaldonado-espol , please verify if that you can download and use the software. check back in with us if there is any problem.

**Comment by pmaldonado-espol** [comment]
> Dear customer @pmaldonado-espol , please verify if that you can download and use the software. check back in with us if there is any problem.

No more changes are needed. Thank you.
